apiVersion: v1
kind: Namespace
metadata:
  name: opentwins
---
apiVersion: v1
kind: Namespace
metadata:
  name: scraping
---
apiVersion: v1
kind: Namespace
metadata:
  name: mysql
---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics
