apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: kubernetes.io/basic-auth
stringData:
  password: $MYSQL_PASSWORD

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: scraping
type: kubernetes.io/basic-auth
stringData:
  password: $MYSQL_PASSWORD